# Generated by Django 5.0.3 on 2024-04-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='blog', verbose_name='изображение')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='публикация')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
