# Generated by Django 5.0.3 on 2024-04-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_category_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукта'},
        ),
    ]
