# Generated by Django 5.0.3 on 2024-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog_previews/', verbose_name='фото')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='публикация')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
            ],
        ),
    ]
