# Generated by Django 5.0.3 on 2024-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_blogpost_product_published_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
    ]
