# Generated by Django 5.0.3 on 2024-05-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_version_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
