# Generated by Django 4.2.2 on 2024-05-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('can_edit_description', 'Edit description'), ('can_edit_published', 'Edit published'), ('can_edit_category', 'Edit category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукта'},
        ),
    ]
