# Generated by Django 5.0.3 on 2024-05-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0019_delete_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(unique=True, verbose_name='номер сорта')),
                ('version_name', models.CharField(max_length=50, verbose_name='сорт продукта')),
                ('version_true', models.BooleanField(default=False, verbose_name='текущий сорт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='main.product', verbose_name='продукт')),
            ],
        ),
    ]
